<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\news_etiquetas;

class NewsEtiquetasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $etiqueta1 = new news_etiquetas(); $etiqueta1->etiqueta = 'Dolo'; $etiqueta1->activo = 1;  $etiqueta1->save();
        $etiqueta2 = new news_etiquetas(); $etiqueta2->etiqueta = 'Censo'; $etiqueta2->activo = 1;  $etiqueta2->save();
        $etiqueta3 = new news_etiquetas(); $etiqueta3->etiqueta = 'Deuda'; $etiqueta3->activo = 1;  $etiqueta3->save();
        $etiqueta4 = new news_etiquetas(); $etiqueta4->etiqueta = 'Diana'; $etiqueta4->activo = 1;  $etiqueta4->save();
        $etiqueta5 = new news_etiquetas(); $etiqueta5->etiqueta = 'Dique'; $etiqueta5->activo = 1;  $etiqueta5->save();
        $etiqueta6 = new news_etiquetas(); $etiqueta6->etiqueta = 'Docks'; $etiqueta6->activo = 1;  $etiqueta6->save();
        $etiqueta7 = new news_etiquetas(); $etiqueta7->etiqueta = 'Ejido'; $etiqueta7->activo = 1;  $etiqueta7->save();
        $etiqueta8 = new news_etiquetas(); $etiqueta8->etiqueta = 'Error'; $etiqueta8->activo = 1;  $etiqueta8->save();
        $etiqueta9 = new news_etiquetas(); $etiqueta9->etiqueta = 'Espia'; $etiqueta9->activo = 1;  $etiqueta9->save();
        $etiqueta10 = new news_etiquetas(); $etiqueta10->etiqueta = 'Cartel'; $etiqueta10->activo = 1;  $etiqueta10->save();
        $etiqueta11 = new news_etiquetas(); $etiqueta11->etiqueta = 'Dibujo'; $etiqueta11->activo = 1;  $etiqueta11->save();
        $etiqueta12 = new news_etiquetas(); $etiqueta12->etiqueta = 'Dinero'; $etiqueta12->activo = 1;  $etiqueta12->save();
        $etiqueta13 = new news_etiquetas(); $etiqueta13->etiqueta = 'Ecosoc'; $etiqueta13->activo = 1;  $etiqueta13->save();
        $etiqueta14 = new news_etiquetas(); $etiqueta14->etiqueta = 'Edicto'; $etiqueta14->activo = 1;  $etiqueta14->save();
        $etiqueta15 = new news_etiquetas(); $etiqueta15->etiqueta = 'Encaje'; $etiqueta15->activo = 1;  $etiqueta15->save();
        $etiqueta16 = new news_etiquetas(); $etiqueta16->etiqueta = 'Endoso'; $etiqueta16->activo = 1;  $etiqueta16->save();
        $etiqueta17 = new news_etiquetas(); $etiqueta17->etiqueta = 'Envase'; $etiqueta17->activo = 1;  $etiqueta17->save();
        $etiqueta18 = new news_etiquetas(); $etiqueta18->etiqueta = 'Enzima'; $etiqueta18->activo = 1;  $etiqueta18->save();
        $etiqueta19 = new news_etiquetas(); $etiqueta19->etiqueta = 'Censura'; $etiqueta19->activo = 1;  $etiqueta19->save();
        $etiqueta20 = new news_etiquetas(); $etiqueta20->etiqueta = 'Despido'; $etiqueta20->activo = 1;  $etiqueta20->save();
        $etiqueta21 = new news_etiquetas(); $etiqueta21->etiqueta = 'Destajo'; $etiqueta21->activo = 1;  $etiqueta21->save();
        $etiqueta22 = new news_etiquetas(); $etiqueta22->etiqueta = 'Diálogo'; $etiqueta22->activo = 1;  $etiqueta22->save();
        $etiqueta23 = new news_etiquetas(); $etiqueta23->etiqueta = 'Dirimir'; $etiqueta23->activo = 1;  $etiqueta23->save();
        $etiqueta24 = new news_etiquetas(); $etiqueta24->etiqueta = 'Divisas'; $etiqueta24->activo = 1;  $etiqueta24->save();
        $etiqueta25 = new news_etiquetas(); $etiqueta25->etiqueta = 'Donante'; $etiqueta25->activo = 1;  $etiqueta25->save();
        $etiqueta26 = new news_etiquetas(); $etiqueta26->etiqueta = 'Dumping'; $etiqueta26->activo = 1;  $etiqueta26->save();
        $etiqueta27 = new news_etiquetas(); $etiqueta27->etiqueta = 'Elector'; $etiqueta27->activo = 1;  $etiqueta27->save();
        $etiqueta28 = new news_etiquetas(); $etiqueta28->etiqueta = 'Embargo'; $etiqueta28->activo = 1;  $etiqueta28->save();
        $etiqueta29 = new news_etiquetas(); $etiqueta29->etiqueta = 'Emblema'; $etiqueta29->activo = 1;  $etiqueta29->save();
        $etiqueta30 = new news_etiquetas(); $etiqueta30->etiqueta = 'Emisión'; $etiqueta30->activo = 1;  $etiqueta30->save();
        $etiqueta31 = new news_etiquetas(); $etiqueta31->etiqueta = 'Emisnet'; $etiqueta31->activo = 1;  $etiqueta31->save();
        $etiqueta32 = new news_etiquetas(); $etiqueta32->etiqueta = 'Empresa'; $etiqueta32->activo = 1;  $etiqueta32->save();
        $etiqueta33 = new news_etiquetas(); $etiqueta33->etiqueta = 'Enervar'; $etiqueta33->activo = 1;  $etiqueta33->save();
        $etiqueta34 = new news_etiquetas(); $etiqueta34->etiqueta = 'Equidad'; $etiqueta34->activo = 1;  $etiqueta34->save();
        $etiqueta35 = new news_etiquetas(); $etiqueta35->etiqueta = 'Escasez'; $etiqueta35->activo = 1;  $etiqueta35->save();
        $etiqueta36 = new news_etiquetas(); $etiqueta36->etiqueta = 'Interés'; $etiqueta36->activo = 1;  $etiqueta36->save();
        $etiqueta37 = new news_etiquetas(); $etiqueta37->etiqueta = 'Mayoría'; $etiqueta37->activo = 1;  $etiqueta37->save();
        $etiqueta38 = new news_etiquetas(); $etiqueta38->etiqueta = 'Pública'; $etiqueta38->activo = 1;  $etiqueta38->save();
        $etiqueta39 = new news_etiquetas(); $etiqueta39->etiqueta = 'Tratado'; $etiqueta39->activo = 1;  $etiqueta39->save();
        $etiqueta40 = new news_etiquetas(); $etiqueta40->etiqueta = 'Coerción'; $etiqueta40->activo = 1;  $etiqueta40->save();
        $etiqueta41 = new news_etiquetas(); $etiqueta41->etiqueta = 'Consenso'; $etiqueta41->activo = 1;  $etiqueta41->save();
        $etiqueta42 = new news_etiquetas(); $etiqueta42->etiqueta = 'Desacato'; $etiqueta42->activo = 1;  $etiqueta42->save();
        $etiqueta43 = new news_etiquetas(); $etiqueta43->etiqueta = 'Desfalco'; $etiqueta43->activo = 1;  $etiqueta43->save();
        $etiqueta44 = new news_etiquetas(); $etiqueta44->etiqueta = 'Desglose'; $etiqueta44->activo = 1;  $etiqueta44->save();
        $etiqueta45 = new news_etiquetas(); $etiqueta45->etiqueta = 'Deslinde'; $etiqueta45->activo = 1;  $etiqueta45->save();
        $etiqueta46 = new news_etiquetas(); $etiqueta46->etiqueta = 'Despejar'; $etiqueta46->activo = 1;  $etiqueta46->save();
        $etiqueta47 = new news_etiquetas(); $etiqueta47->etiqueta = 'Destacar'; $etiqueta47->activo = 1;  $etiqueta47->save();
        $etiqueta48 = new news_etiquetas(); $etiqueta48->etiqueta = 'Destruir'; $etiqueta48->activo = 1;  $etiqueta48->save();
        $etiqueta49 = new news_etiquetas(); $etiqueta49->etiqueta = 'Diáspora'; $etiqueta49->activo = 1;  $etiqueta49->save();
        $etiqueta50 = new news_etiquetas(); $etiqueta50->etiqueta = 'Dictamen'; $etiqueta50->activo = 1;  $etiqueta50->save();
        $etiqueta51 = new news_etiquetas(); $etiqueta51->etiqueta = 'Difusión'; $etiqueta51->activo = 1;  $etiqueta51->save();
        $etiqueta52 = new news_etiquetas(); $etiqueta52->etiqueta = 'Dilación'; $etiqueta52->activo = 1;  $etiqueta52->save();
        $etiqueta53 = new news_etiquetas(); $etiqueta53->etiqueta = 'Dispensa'; $etiqueta53->activo = 1;  $etiqueta53->save();
        $etiqueta54 = new news_etiquetas(); $etiqueta54->etiqueta = 'Doctrina'; $etiqueta54->activo = 1;  $etiqueta54->save();
        $etiqueta55 = new news_etiquetas(); $etiqueta55->etiqueta = 'Donación'; $etiqueta55->activo = 1;  $etiqueta55->save();
        $etiqueta56 = new news_etiquetas(); $etiqueta56->etiqueta = 'Ecología'; $etiqueta56->activo = 1;  $etiqueta56->save();
        $etiqueta57 = new news_etiquetas(); $etiqueta57->etiqueta = 'Economía'; $etiqueta57->activo = 1;  $etiqueta57->save();
        $etiqueta58 = new news_etiquetas(); $etiqueta58->etiqueta = 'Eficacia'; $etiqueta58->activo = 1;  $etiqueta58->save();
        $etiqueta59 = new news_etiquetas(); $etiqueta59->etiqueta = 'Elección'; $etiqueta59->activo = 1;  $etiqueta59->save();
        $etiqueta60 = new news_etiquetas(); $etiqueta60->etiqueta = 'Embajada'; $etiqueta60->activo = 1;  $etiqueta60->save();
        $etiqueta61 = new news_etiquetas(); $etiqueta61->etiqueta = 'Emisoras'; $etiqueta61->activo = 1;  $etiqueta61->save();
        $etiqueta62 = new news_etiquetas(); $etiqueta62->etiqueta = 'Encuesta'; $etiqueta62->activo = 1;  $etiqueta62->save();
        $etiqueta63 = new news_etiquetas(); $etiqueta63->etiqueta = 'Enmienda'; $etiqueta63->activo = 1;  $etiqueta63->save();
        $etiqueta64 = new news_etiquetas(); $etiqueta64->etiqueta = 'Ensenada'; $etiqueta64->activo = 1;  $etiqueta64->save();
        $etiqueta65 = new news_etiquetas(); $etiqueta65->etiqueta = 'Entenado'; $etiqueta65->activo = 1;  $etiqueta65->save();
        $etiqueta66 = new news_etiquetas(); $etiqueta66->etiqueta = 'Epiqueya'; $etiqueta66->activo = 1;  $etiqueta66->save();
        $etiqueta67 = new news_etiquetas(); $etiqueta67->etiqueta = 'Esquirol'; $etiqueta67->activo = 1;  $etiqueta67->save();
        $etiqueta68 = new news_etiquetas(); $etiqueta68->etiqueta = 'Gabinete'; $etiqueta68->activo = 1;  $etiqueta68->save();
        $etiqueta69 = new news_etiquetas(); $etiqueta69->etiqueta = 'Inter se'; $etiqueta69->activo = 1;  $etiqueta69->save();
        $etiqueta70 = new news_etiquetas(); $etiqueta70->etiqueta = 'Interpol'; $etiqueta70->activo = 1;  $etiqueta70->save();
        $etiqueta71 = new news_etiquetas(); $etiqueta71->etiqueta = 'Minorías'; $etiqueta71->activo = 1;  $etiqueta71->save();
        $etiqueta72 = new news_etiquetas(); $etiqueta72->etiqueta = 'Autarquía'; $etiqueta72->activo = 1;  $etiqueta72->save();
        $etiqueta73 = new news_etiquetas(); $etiqueta73->etiqueta = 'Civilidad'; $etiqueta73->activo = 1;  $etiqueta73->save();
        $etiqueta74 = new news_etiquetas(); $etiqueta74->etiqueta = 'Demagogia'; $etiqueta74->activo = 1;  $etiqueta74->save();
        $etiqueta75 = new news_etiquetas(); $etiqueta75->etiqueta = 'Depresión'; $etiqueta75->activo = 1;  $etiqueta75->save();
        $etiqueta76 = new news_etiquetas(); $etiqueta76->etiqueta = 'Derivados'; $etiqueta76->activo = 1;  $etiqueta76->save();
        $etiqueta77 = new news_etiquetas(); $etiqueta77->etiqueta = 'Desaforar'; $etiqueta77->activo = 1;  $etiqueta77->save();
        $etiqueta78 = new news_etiquetas(); $etiqueta78->etiqueta = 'Desahucio'; $etiqueta78->activo = 1;  $etiqueta78->save();
        $etiqueta79 = new news_etiquetas(); $etiqueta79->etiqueta = 'Descuento'; $etiqueta79->activo = 1;  $etiqueta79->save();
        $etiqueta80 = new news_etiquetas(); $etiqueta80->etiqueta = 'Deserción'; $etiqueta80->activo = 1;  $etiqueta80->save();
        $etiqueta81 = new news_etiquetas(); $etiqueta81->etiqueta = 'Destierro'; $etiqueta81->activo = 1;  $etiqueta81->save();
        $etiqueta82 = new news_etiquetas(); $etiqueta82->etiqueta = 'Detención'; $etiqueta82->activo = 1;  $etiqueta82->save();
        $etiqueta83 = new news_etiquetas(); $etiqueta83->etiqueta = 'Deterioro'; $etiqueta83->activo = 1;  $etiqueta83->save();
        $etiqueta84 = new news_etiquetas(); $etiqueta84->etiqueta = 'Día hábil'; $etiqueta84->activo = 1;  $etiqueta84->save();
        $etiqueta85 = new news_etiquetas(); $etiqueta85->etiqueta = 'Dilatorio'; $etiqueta85->activo = 1;  $etiqueta85->save();
        $etiqueta86 = new news_etiquetas(); $etiqueta86->etiqueta = 'Directiva'; $etiqueta86->activo = 1;  $etiqueta86->save();
        $etiqueta87 = new news_etiquetas(); $etiqueta87->etiqueta = 'Disuasión'; $etiqueta87->activo = 1;  $etiqueta87->save();
        $etiqueta88 = new news_etiquetas(); $etiqueta88->etiqueta = 'Dividendo'; $etiqueta88->activo = 1;  $etiqueta88->save();
        $etiqueta89 = new news_etiquetas(); $etiqueta89->etiqueta = 'Do ut des'; $etiqueta89->activo = 1;  $etiqueta89->save();
        $etiqueta90 = new news_etiquetas(); $etiqueta90->etiqueta = 'Documento'; $etiqueta90->activo = 1;  $etiqueta90->save();
        $etiqueta91 = new news_etiquetas(); $etiqueta91->etiqueta = 'Domicilio'; $etiqueta91->activo = 1;  $etiqueta91->save();
        $etiqueta92 = new news_etiquetas(); $etiqueta92->etiqueta = 'Donatario'; $etiqueta92->activo = 1;  $etiqueta92->save();
        $etiqueta93 = new news_etiquetas(); $etiqueta93->etiqueta = 'Dow jones'; $etiqueta93->activo = 1;  $etiqueta93->save();
        $etiqueta94 = new news_etiquetas(); $etiqueta94->etiqueta = 'Draw back'; $etiqueta94->activo = 1;  $etiqueta94->save();
        $etiqueta95 = new news_etiquetas(); $etiqueta95->etiqueta = 'Ecu verde'; $etiqueta95->activo = 1;  $etiqueta95->save();
        $etiqueta96 = new news_etiquetas(); $etiqueta96->etiqueta = 'Ejecución'; $etiqueta96->activo = 1;  $etiqueta96->save();
        $etiqueta97 = new news_etiquetas(); $etiqueta97->etiqueta = 'Electores'; $etiqueta97->activo = 1;  $etiqueta97->save();
        $etiqueta98 = new news_etiquetas(); $etiqueta98->etiqueta = 'Embajador'; $etiqueta98->activo = 1;  $etiqueta98->save();
        $etiqueta99 = new news_etiquetas(); $etiqueta99->etiqueta = 'Emboscada'; $etiqueta99->activo = 1;  $etiqueta99->save();
        $etiqueta100 = new news_etiquetas(); $etiqueta100->etiqueta = 'Escribano'; $etiqueta100->activo = 1;  $etiqueta100->save();
        $etiqueta101 = new news_etiquetas(); $etiqueta101->etiqueta = 'Escuadrón'; $etiqueta101->activo = 1;  $etiqueta101->save();
        $etiqueta102 = new news_etiquetas(); $etiqueta102->etiqueta = 'Espionaje'; $etiqueta102->activo = 1;  $etiqueta102->save();
        $etiqueta103 = new news_etiquetas(); $etiqueta103->etiqueta = 'Ideología'; $etiqueta103->activo = 1;  $etiqueta103->save();
        $etiqueta104 = new news_etiquetas(); $etiqueta104->etiqueta = 'Legalidad'; $etiqueta104->activo = 1;  $etiqueta104->save();
        $etiqueta105 = new news_etiquetas(); $etiqueta105->etiqueta = 'Burocracia'; $etiqueta105->activo = 1;  $etiqueta105->save();
        $etiqueta106 = new news_etiquetas(); $etiqueta106->etiqueta = 'Ciudadanía'; $etiqueta106->activo = 1;  $etiqueta106->save();
        $etiqueta107 = new news_etiquetas(); $etiqueta107->etiqueta = 'Derelictio'; $etiqueta107->activo = 1;  $etiqueta107->save();
        $etiqueta108 = new news_etiquetas(); $etiqueta108->etiqueta = 'Derogación'; $etiqueta108->activo = 1;  $etiqueta108->save();
        $etiqueta109 = new news_etiquetas(); $etiqueta109->etiqueta = 'Desarrollo'; $etiqueta109->activo = 1;  $etiqueta109->save();
        $etiqueta110 = new news_etiquetas(); $etiqueta110->etiqueta = 'Desembarco'; $etiqueta110->activo = 1;  $etiqueta110->save();
        $etiqueta111 = new news_etiquetas(); $etiqueta111->etiqueta = 'Desgrávame'; $etiqueta111->activo = 1;  $etiqueta111->save();
        $etiqueta112 = new news_etiquetas(); $etiqueta112->etiqueta = 'Desplazado'; $etiqueta112->activo = 1;  $etiqueta112->save();
        $etiqueta113 = new news_etiquetas(); $etiqueta113->etiqueta = 'Despliegue'; $etiqueta113->activo = 1;  $etiqueta113->save();
        $etiqueta114 = new news_etiquetas(); $etiqueta114->etiqueta = 'Destilería'; $etiqueta114->activo = 1;  $etiqueta114->save();
        $etiqueta115 = new news_etiquetas(); $etiqueta115->etiqueta = 'Destructor'; $etiqueta115->activo = 1;  $etiqueta115->save();
        $etiqueta116 = new news_etiquetas(); $etiqueta116->etiqueta = 'Detallista'; $etiqueta116->activo = 1;  $etiqueta116->save();
        $etiqueta117 = new news_etiquetas(); $etiqueta117->etiqueta = 'Devolutivo'; $etiqueta117->activo = 1;  $etiqueta117->save();
        $etiqueta118 = new news_etiquetas(); $etiqueta118->etiqueta = 'Dies a quo'; $etiqueta118->activo = 1;  $etiqueta118->save();
        $etiqueta119 = new news_etiquetas(); $etiqueta119->etiqueta = 'Diligencia'; $etiqueta119->activo = 1;  $etiqueta119->save();
        $etiqueta120 = new news_etiquetas(); $etiqueta120->etiqueta = 'Diplomacia'; $etiqueta120->activo = 1;  $etiqueta120->save();
        $etiqueta121 = new news_etiquetas(); $etiqueta121->etiqueta = 'Diputación'; $etiqueta121->activo = 1;  $etiqueta121->save();
        $etiqueta122 = new news_etiquetas(); $etiqueta122->etiqueta = 'Disipación'; $etiqueta122->activo = 1;  $etiqueta122->save();
        $etiqueta123 = new news_etiquetas(); $etiqueta123->etiqueta = 'Disolución'; $etiqueta123->activo = 1;  $etiqueta123->save();
        $etiqueta124 = new news_etiquetas(); $etiqueta124->etiqueta = 'Dispersión'; $etiqueta124->activo = 1;  $etiqueta124->save();
        $etiqueta125 = new news_etiquetas(); $etiqueta125->etiqueta = 'Dividendos'; $etiqueta125->activo = 1;  $etiqueta125->save();
        $etiqueta126 = new news_etiquetas(); $etiqueta126->etiqueta = 'Documental'; $etiqueta126->activo = 1;  $etiqueta126->save();
        $etiqueta127 = new news_etiquetas(); $etiqueta127->etiqueta = 'Ecodumping'; $etiqueta127->activo = 1;  $etiqueta127->save();
        $etiqueta128 = new news_etiquetas(); $etiqueta128->etiqueta = 'Ecosistema'; $etiqueta128->activo = 1;  $etiqueta128->save();
        $etiqueta129 = new news_etiquetas(); $etiqueta129->etiqueta = 'Eficiencia'; $etiqueta129->activo = 1;  $etiqueta129->save();
        $etiqueta130 = new news_etiquetas(); $etiqueta130->etiqueta = 'Ejecutoria'; $etiqueta130->activo = 1;  $etiqueta130->save();
        $etiqueta131 = new news_etiquetas(); $etiqueta131->etiqueta = 'Emancipado'; $etiqueta131->activo = 1;  $etiqueta131->save();
        $etiqueta132 = new news_etiquetas(); $etiqueta132->etiqueta = 'Emigración'; $etiqueta132->activo = 1;  $etiqueta132->save();
        $etiqueta133 = new news_etiquetas(); $etiqueta133->etiqueta = 'Empresario'; $etiqueta133->activo = 1;  $etiqueta133->save();
        $etiqueta134 = new news_etiquetas(); $etiqueta134->etiqueta = 'Empresitos'; $etiqueta134->activo = 1;  $etiqueta134->save();
        $etiqueta135 = new news_etiquetas(); $etiqueta135->etiqueta = 'Empréstito'; $etiqueta135->activo = 1;  $etiqueta135->save();
        $etiqueta136 = new news_etiquetas(); $etiqueta136->etiqueta = 'Entredicho'; $etiqueta136->activo = 1;  $etiqueta136->save();
        $etiqueta137 = new news_etiquetas(); $etiqueta137->etiqueta = 'Entrevista'; $etiqueta137->activo = 1;  $etiqueta137->save();
        $etiqueta138 = new news_etiquetas(); $etiqueta138->etiqueta = 'Erga omnes'; $etiqueta138->activo = 1;  $etiqueta138->save();
        $etiqueta139 = new news_etiquetas(); $etiqueta139->etiqueta = 'Ínter alia'; $etiqueta139->activo = 1;  $etiqueta139->save();
        $etiqueta140 = new news_etiquetas(); $etiqueta140->etiqueta = 'Interfecto'; $etiqueta140->activo = 1;  $etiqueta140->save();
        $etiqueta141 = new news_etiquetas(); $etiqueta141->etiqueta = 'Pluralismo'; $etiqueta141->activo = 1;  $etiqueta141->save();
        $etiqueta142 = new news_etiquetas(); $etiqueta142->etiqueta = 'Terrorismo'; $etiqueta142->activo = 1;  $etiqueta142->save();
        $etiqueta143 = new news_etiquetas(); $etiqueta143->etiqueta = 'Tolerancia'; $etiqueta143->activo = 1;  $etiqueta143->save();
        $etiqueta144 = new news_etiquetas(); $etiqueta144->etiqueta = 'Absolutismo'; $etiqueta144->activo = 1;  $etiqueta144->save();
        $etiqueta145 = new news_etiquetas(); $etiqueta145->etiqueta = 'Alternancia'; $etiqueta145->activo = 1;  $etiqueta145->save();
        $etiqueta146 = new news_etiquetas(); $etiqueta146->etiqueta = 'Competencia'; $etiqueta146->activo = 1;  $etiqueta146->save();
        $etiqueta147 = new news_etiquetas(); $etiqueta147->etiqueta = 'Descubierta'; $etiqueta147->activo = 1;  $etiqueta147->save();
        $etiqueta148 = new news_etiquetas(); $etiqueta148->etiqueta = 'Descubierto'; $etiqueta148->activo = 1;  $etiqueta148->save();
        $etiqueta149 = new news_etiquetas(); $etiqueta149->etiqueta = 'Devaluación'; $etiqueta149->activo = 1;  $etiqueta149->save();
        $etiqueta150 = new news_etiquetas(); $etiqueta150->etiqueta = 'Días fastos'; $etiqueta150->activo = 1;  $etiqueta150->save();
        $etiqueta151 = new news_etiquetas(); $etiqueta151->etiqueta = 'Digitalizar'; $etiqueta151->activo = 1;  $etiqueta151->save();
        $etiqueta152 = new news_etiquetas(); $etiqueta152->etiqueta = 'Discriminar'; $etiqueta152->activo = 1;  $etiqueta152->save();
        $etiqueta153 = new news_etiquetas(); $etiqueta153->etiqueta = 'Dispositivo'; $etiqueta153->activo = 1;  $etiqueta153->save();
        $etiqueta154 = new news_etiquetas(); $etiqueta154->etiqueta = 'Divulgación'; $etiqueta154->activo = 1;  $etiqueta154->save();
        $etiqueta155 = new news_etiquetas(); $etiqueta155->etiqueta = 'Elasticidad'; $etiqueta155->activo = 1;  $etiqueta155->save();
        $etiqueta156 = new news_etiquetas(); $etiqueta156->etiqueta = 'Enajenación'; $etiqueta156->activo = 1;  $etiqueta156->save();
        $etiqueta157 = new news_etiquetas(); $etiqueta157->etiqueta = 'Imaginación'; $etiqueta157->activo = 1;  $etiqueta157->save();
        $etiqueta158 = new news_etiquetas(); $etiqueta158->etiqueta = 'Inter ipsos'; $etiqueta158->activo = 1;  $etiqueta158->save();
        $etiqueta159 = new news_etiquetas(); $etiqueta159->etiqueta = 'Interdictos'; $etiqueta159->activo = 1;  $etiqueta159->save();
        $etiqueta160 = new news_etiquetas(); $etiqueta160->etiqueta = 'Interdictum'; $etiqueta160->activo = 1;  $etiqueta160->save();
        $etiqueta161 = new news_etiquetas(); $etiqueta161->etiqueta = 'Internuncio'; $etiqueta161->activo = 1;  $etiqueta161->save();
        $etiqueta162 = new news_etiquetas(); $etiqueta162->etiqueta = 'Plutocracia'; $etiqueta162->activo = 1;  $etiqueta162->save();
        $etiqueta163 = new news_etiquetas(); $etiqueta163->etiqueta = 'Autocoerción'; $etiqueta163->activo = 1;  $etiqueta163->save();
        $etiqueta164 = new news_etiquetas(); $etiqueta164->etiqueta = 'Constitución'; $etiqueta164->activo = 1;  $etiqueta164->save();
        $etiqueta165 = new news_etiquetas(); $etiqueta165->etiqueta = 'Desaparecido'; $etiqueta165->activo = 1;  $etiqueta165->save();
        $etiqueta166 = new news_etiquetas(); $etiqueta166->etiqueta = 'Descendiente'; $etiqueta166->activo = 1;  $etiqueta166->save();
        $etiqueta167 = new news_etiquetas(); $etiqueta167->etiqueta = 'Desorganizar'; $etiqueta167->activo = 1;  $etiqueta167->save();
        $etiqueta168 = new news_etiquetas(); $etiqueta168->etiqueta = 'Desperdicios'; $etiqueta168->activo = 1;  $etiqueta168->save();
        $etiqueta169 = new news_etiquetas(); $etiqueta169->etiqueta = 'Destinatario'; $etiqueta169->activo = 1;  $etiqueta169->save();
        $etiqueta170 = new news_etiquetas(); $etiqueta170->etiqueta = 'Día bancario'; $etiqueta170->activo = 1;  $etiqueta170->save();
        $etiqueta171 = new news_etiquetas(); $etiqueta171->etiqueta = 'Dies ad quem'; $etiqueta171->activo = 1;  $etiqueta171->save();
        $etiqueta172 = new news_etiquetas(); $etiqueta172->etiqueta = 'Discrecional'; $etiqueta172->activo = 1;  $etiqueta172->save();
        $etiqueta173 = new news_etiquetas(); $etiqueta173->etiqueta = 'Elegibilidad'; $etiqueta173->activo = 1;  $etiqueta173->save();
        $etiqueta174 = new news_etiquetas(); $etiqueta174->etiqueta = 'Emancipacion'; $etiqueta174->activo = 1;  $etiqueta174->save();
        $etiqueta175 = new news_etiquetas(); $etiqueta175->etiqueta = 'Especulación'; $etiqueta175->activo = 1;  $etiqueta175->save();
        $etiqueta176 = new news_etiquetas(); $etiqueta176->etiqueta = 'Guerra civil'; $etiqueta176->activo = 1;  $etiqueta176->save();
        $etiqueta177 = new news_etiquetas(); $etiqueta177->etiqueta = 'Interdicción'; $etiqueta177->activo = 1;  $etiqueta177->save();
        $etiqueta178 = new news_etiquetas(); $etiqueta178->etiqueta = 'Intervención'; $etiqueta178->activo = 1;  $etiqueta178->save();
        $etiqueta179 = new news_etiquetas(); $etiqueta179->etiqueta = 'Racionalidad'; $etiqueta179->activo = 1;  $etiqueta179->save();
        $etiqueta180 = new news_etiquetas(); $etiqueta180->etiqueta = 'Reciprocidad'; $etiqueta180->activo = 1;  $etiqueta180->save();
        $etiqueta181 = new news_etiquetas(); $etiqueta181->etiqueta = 'Reflexividad'; $etiqueta181->activo = 1;  $etiqueta181->save();
        $etiqueta182 = new news_etiquetas(); $etiqueta182->etiqueta = 'Ambientalismo'; $etiqueta182->activo = 1;  $etiqueta182->save();
        $etiqueta183 = new news_etiquetas(); $etiqueta183->etiqueta = 'Certificación'; $etiqueta183->activo = 1;  $etiqueta183->save();
        $etiqueta184 = new news_etiquetas(); $etiqueta184->etiqueta = 'Derecho penal'; $etiqueta184->activo = 1;  $etiqueta184->save();
        $etiqueta185 = new news_etiquetas(); $etiqueta185->etiqueta = 'Desheredación'; $etiqueta185->activo = 1;  $etiqueta185->save();
        $etiqueta186 = new news_etiquetas(); $etiqueta186->etiqueta = 'Desistimiento'; $etiqueta186->activo = 1;  $etiqueta186->save();
        $etiqueta187 = new news_etiquetas(); $etiqueta187->etiqueta = 'Desobediencia'; $etiqueta187->activo = 1;  $etiqueta187->save();
        $etiqueta188 = new news_etiquetas(); $etiqueta188->etiqueta = 'Deuda externa'; $etiqueta188->activo = 1;  $etiqueta188->save();
        $etiqueta189 = new news_etiquetas(); $etiqueta189->etiqueta = 'Deuda pública'; $etiqueta189->activo = 1;  $etiqueta189->save();
        $etiqueta190 = new news_etiquetas(); $etiqueta190->etiqueta = 'Días nefastos'; $etiqueta190->activo = 1;  $etiqueta190->save();
        $etiqueta191 = new news_etiquetas(); $etiqueta191->etiqueta = 'Dolo eventual'; $etiqueta191->activo = 1;  $etiqueta191->save();
        $etiqueta192 = new news_etiquetas(); $etiqueta192->etiqueta = 'Ecoetiquetado'; $etiqueta192->activo = 1;  $etiqueta192->save();
        $etiqueta193 = new news_etiquetas(); $etiqueta193->etiqueta = 'Emplazamiento'; $etiqueta193->activo = 1;  $etiqueta193->save();
        $etiqueta194 = new news_etiquetas(); $etiqueta194->etiqueta = 'Espacio aéreo'; $etiqueta194->activo = 1;  $etiqueta194->save();
        $etiqueta195 = new news_etiquetas(); $etiqueta195->etiqueta = 'Globalización'; $etiqueta195->activo = 1;  $etiqueta195->save();
        $etiqueta196 = new news_etiquetas(); $etiqueta196->etiqueta = 'Instituciones'; $etiqueta196->activo = 1;  $etiqueta196->save();
        $etiqueta197 = new news_etiquetas(); $etiqueta197->etiqueta = 'Interés legal'; $etiqueta197->activo = 1;  $etiqueta197->save();
        $etiqueta198 = new news_etiquetas(); $etiqueta198->etiqueta = 'Intermediario'; $etiqueta198->activo = 1;  $etiqueta198->save();
        $etiqueta199 = new news_etiquetas(); $etiqueta199->etiqueta = 'Laissez faire'; $etiqueta199->activo = 1;  $etiqueta199->save();
        $etiqueta200 = new news_etiquetas(); $etiqueta200->etiqueta = 'Privatización'; $etiqueta200->activo = 1;  $etiqueta200->save();
        $etiqueta201 = new news_etiquetas(); $etiqueta201->etiqueta = 'Razón pública'; $etiqueta201->activo = 1;  $etiqueta201->save();
        $etiqueta202 = new news_etiquetas(); $etiqueta202->etiqueta = 'Razonabilidad'; $etiqueta202->activo = 1;  $etiqueta202->save();
        $etiqueta203 = new news_etiquetas(); $etiqueta203->etiqueta = 'Derecho de uso'; $etiqueta203->activo = 1;  $etiqueta203->save();
        $etiqueta204 = new news_etiquetas(); $etiqueta204->etiqueta = 'Derecho propio'; $etiqueta204->activo = 1;  $etiqueta204->save();
        $etiqueta205 = new news_etiquetas(); $etiqueta205->etiqueta = 'Derecho social'; $etiqueta205->activo = 1;  $etiqueta205->save();
        $etiqueta206 = new news_etiquetas(); $etiqueta206->etiqueta = 'Descubrimiento'; $etiqueta206->activo = 1;  $etiqueta206->save();
        $etiqueta207 = new news_etiquetas(); $etiqueta207->etiqueta = 'Diario oficial'; $etiqueta207->activo = 1;  $etiqueta207->save();
        $etiqueta208 = new news_etiquetas(); $etiqueta208->etiqueta = 'Días inhábiles'; $etiqueta208->activo = 1;  $etiqueta208->save();
        $etiqueta209 = new news_etiquetas(); $etiqueta209->etiqueta = 'Discernimiento'; $etiqueta209->activo = 1;  $etiqueta209->save();
        $etiqueta210 = new news_etiquetas(); $etiqueta210->etiqueta = 'Discriminación'; $etiqueta210->activo = 1;  $etiqueta210->save();
        $etiqueta211 = new news_etiquetas(); $etiqueta211->etiqueta = 'Disponibilidad'; $etiqueta211->activo = 1;  $etiqueta211->save();
        $etiqueta212 = new news_etiquetas(); $etiqueta212->etiqueta = 'Doctrina calvo'; $etiqueta212->activo = 1;  $etiqueta212->save();
        $etiqueta213 = new news_etiquetas(); $etiqueta213->etiqueta = 'Doctrina drago'; $etiqueta213->activo = 1;  $etiqueta213->save();
        $etiqueta214 = new news_etiquetas(); $etiqueta214->etiqueta = 'Dumping social'; $etiqueta214->activo = 1;  $etiqueta214->save();
        $etiqueta215 = new news_etiquetas(); $etiqueta215->etiqueta = 'Elusion fiscal'; $etiqueta215->activo = 1;  $etiqueta215->save();
        $etiqueta216 = new news_etiquetas(); $etiqueta216->etiqueta = 'Error estándar'; $etiqueta216->activo = 1;  $etiqueta216->save();
        $etiqueta217 = new news_etiquetas(); $etiqueta217->etiqueta = 'Error judicial'; $etiqueta217->activo = 1;  $etiqueta217->save();
        $etiqueta218 = new news_etiquetas(); $etiqueta218->etiqueta = 'Especificación'; $etiqueta218->activo = 1;  $etiqueta218->save();
        $etiqueta219 = new news_etiquetas(); $etiqueta219->etiqueta = 'Inter sicarios'; $etiqueta219->activo = 1;  $etiqueta219->save();
        $etiqueta220 = new news_etiquetas(); $etiqueta220->etiqueta = 'Interrogatorio'; $etiqueta220->activo = 1;  $etiqueta220->save();
        $etiqueta221 = new news_etiquetas(); $etiqueta221->etiqueta = 'Proteccionismo'; $etiqueta221->activo = 1;  $etiqueta221->save();
        $etiqueta222 = new news_etiquetas(); $etiqueta222->etiqueta = 'Unilateralismo'; $etiqueta222->activo = 1;  $etiqueta222->save();
        $etiqueta223 = new news_etiquetas(); $etiqueta223->etiqueta = 'Autolegislación'; $etiqueta223->activo = 1;  $etiqueta223->save();
        $etiqueta224 = new news_etiquetas(); $etiqueta224->etiqueta = 'Derecho privado'; $etiqueta224->activo = 1;  $etiqueta224->save();
        $etiqueta225 = new news_etiquetas(); $etiqueta225->etiqueta = 'Derecho público'; $etiqueta225->activo = 1;  $etiqueta225->save();
        $etiqueta226 = new news_etiquetas(); $etiqueta226->etiqueta = 'Despenalización'; $etiqueta226->activo = 1;  $etiqueta226->save();
        $etiqueta227 = new news_etiquetas(); $etiqueta227->etiqueta = 'Doctrina monroe'; $etiqueta227->activo = 1;  $etiqueta227->save();
        $etiqueta228 = new news_etiquetas(); $etiqueta228->etiqueta = 'Dominio eminent'; $etiqueta228->activo = 1;  $etiqueta228->save();
        $etiqueta229 = new news_etiquetas(); $etiqueta229->etiqueta = 'Dominio público'; $etiqueta229->activo = 1;  $etiqueta229->save();
        $etiqueta230 = new news_etiquetas(); $etiqueta230->etiqueta = 'Encuesta piloto'; $etiqueta230->activo = 1;  $etiqueta230->save();
        $etiqueta231 = new news_etiquetas(); $etiqueta231->etiqueta = 'Envase múltiple'; $etiqueta231->activo = 1;  $etiqueta231->save();
        $etiqueta232 = new news_etiquetas(); $etiqueta232->etiqueta = 'Equipo especial'; $etiqueta232->activo = 1;  $etiqueta232->save();
        $etiqueta233 = new news_etiquetas(); $etiqueta233->etiqueta = 'Equipo terminal'; $etiqueta233->activo = 1;  $etiqueta233->save();
        $etiqueta234 = new news_etiquetas(); $etiqueta234->etiqueta = 'Espacio de vida'; $etiqueta234->activo = 1;  $etiqueta234->save();
        $etiqueta235 = new news_etiquetas(); $etiqueta235->etiqueta = 'Intentis oculis'; $etiqueta235->activo = 1;  $etiqueta235->save();
        $etiqueta236 = new news_etiquetas(); $etiqueta236->etiqueta = 'Interaccionismo'; $etiqueta236->activo = 1;  $etiqueta236->save();
        $etiqueta237 = new news_etiquetas(); $etiqueta237->etiqueta = 'Interés público'; $etiqueta237->activo = 1;  $etiqueta237->save();
        $etiqueta238 = new news_etiquetas(); $etiqueta238->etiqueta = 'Opinión pública'; $etiqueta238->activo = 1;  $etiqueta238->save();
        $etiqueta239 = new news_etiquetas(); $etiqueta239->etiqueta = 'Bienes políticos'; $etiqueta239->activo = 1;  $etiqueta239->save();
        $etiqueta240 = new news_etiquetas(); $etiqueta240->etiqueta = 'Derecho positivo'; $etiqueta240->activo = 1;  $etiqueta240->save();
        $etiqueta241 = new news_etiquetas(); $etiqueta241->etiqueta = 'Derechos civiles'; $etiqueta241->activo = 1;  $etiqueta241->save();
        $etiqueta242 = new news_etiquetas(); $etiqueta242->etiqueta = 'Derechos humanos'; $etiqueta242->activo = 1;  $etiqueta242->save();
        $etiqueta243 = new news_etiquetas(); $etiqueta243->etiqueta = 'Descarga directa'; $etiqueta243->activo = 1;  $etiqueta243->save();
        $etiqueta244 = new news_etiquetas(); $etiqueta244->etiqueta = 'Desconcentración'; $etiqueta244->activo = 1;  $etiqueta244->save();
        $etiqueta245 = new news_etiquetas(); $etiqueta245->etiqueta = 'Desgrávame único'; $etiqueta245->activo = 1;  $etiqueta245->save();
        $etiqueta246 = new news_etiquetas(); $etiqueta246->etiqueta = 'Desmantelamiento'; $etiqueta246->activo = 1;  $etiqueta246->save();
        $etiqueta247 = new news_etiquetas(); $etiqueta247->etiqueta = 'Desmutualización'; $etiqueta247->activo = 1;  $etiqueta247->save();
        $etiqueta248 = new news_etiquetas(); $etiqueta248->etiqueta = 'Detención ilegal'; $etiqueta248->activo = 1;  $etiqueta248->save();
        $etiqueta249 = new news_etiquetas(); $etiqueta249->etiqueta = 'Dilemas sociales'; $etiqueta249->activo = 1;  $etiqueta249->save();
        $etiqueta250 = new news_etiquetas(); $etiqueta250->etiqueta = 'Disenso político'; $etiqueta250->activo = 1;  $etiqueta250->save();
        $etiqueta251 = new news_etiquetas(); $etiqueta251->etiqueta = 'Doble imposición'; $etiqueta251->activo = 1;  $etiqueta251->save();
        $etiqueta252 = new news_etiquetas(); $etiqueta252->etiqueta = 'Doctrina estrada'; $etiqueta252->activo = 1;  $etiqueta252->save();
        $etiqueta253 = new news_etiquetas(); $etiqueta253->etiqueta = 'Domicilio fiscal'; $etiqueta253->activo = 1;  $etiqueta253->save();
        $etiqueta254 = new news_etiquetas(); $etiqueta254->etiqueta = 'Ducto (pipeline)'; $etiqueta254->activo = 1;  $etiqueta254->save();
        $etiqueta255 = new news_etiquetas(); $etiqueta255->etiqueta = 'Editor de libros'; $etiqueta255->activo = 1;  $etiqueta255->save();
        $etiqueta256 = new news_etiquetas(); $etiqueta256->etiqueta = 'Educación cívica'; $etiqueta256->activo = 1;  $etiqueta256->save();
        $etiqueta257 = new news_etiquetas(); $etiqueta257->etiqueta = 'Elección parcial'; $etiqueta257->activo = 1;  $etiqueta257->save();
        $etiqueta258 = new news_etiquetas(); $etiqueta258->etiqueta = 'Empresa conjunta'; $etiqueta258->activo = 1;  $etiqueta258->save();
        $etiqueta259 = new news_etiquetas(); $etiqueta259->etiqueta = 'Escritura social'; $etiqueta259->activo = 1;  $etiqueta259->save();
        $etiqueta260 = new news_etiquetas(); $etiqueta260->etiqueta = 'Poder hegemónico'; $etiqueta260->activo = 1;  $etiqueta260->save();
        $etiqueta261 = new news_etiquetas(); $etiqueta261->etiqueta = 'Derecho a la vida'; $etiqueta261->activo = 1;  $etiqueta261->save();
        $etiqueta262 = new news_etiquetas(); $etiqueta262->etiqueta = 'Derecho del tanto'; $etiqueta262->activo = 1;  $etiqueta262->save();
        $etiqueta263 = new news_etiquetas(); $etiqueta263->etiqueta = 'Derecho subjetivo'; $etiqueta263->activo = 1;  $etiqueta263->save();
        $etiqueta264 = new news_etiquetas(); $etiqueta264->etiqueta = 'Derechos sociales'; $etiqueta264->activo = 1;  $etiqueta264->save();
        $etiqueta265 = new news_etiquetas(); $etiqueta265->etiqueta = 'Descentralización'; $etiqueta265->activo = 1;  $etiqueta265->save();
        $etiqueta266 = new news_etiquetas(); $etiqueta266->etiqueta = 'Diagrama de flujo'; $etiqueta266->activo = 1;  $etiqueta266->save();
        $etiqueta267 = new news_etiquetas(); $etiqueta267->etiqueta = 'Dictamen pericial'; $etiqueta267->activo = 1;  $etiqueta267->save();
        $etiqueta268 = new news_etiquetas(); $etiqueta268->etiqueta = 'Documento privado'; $etiqueta268->activo = 1;  $etiqueta268->save();
        $etiqueta269 = new news_etiquetas(); $etiqueta269->etiqueta = 'Documento público'; $etiqueta269->activo = 1;  $etiqueta269->save();
        $etiqueta270 = new news_etiquetas(); $etiqueta270->etiqueta = 'Efecto devolutivo'; $etiqueta270->activo = 1;  $etiqueta270->save();
        $etiqueta271 = new news_etiquetas(); $etiqueta271->etiqueta = 'Efecto suspensivo'; $etiqueta271->activo = 1;  $etiqueta271->save();
        $etiqueta272 = new news_etiquetas(); $etiqueta272->etiqueta = 'Encuesta de panel'; $etiqueta272->activo = 1;  $etiqueta272->save();
        $etiqueta273 = new news_etiquetas(); $etiqueta273->etiqueta = 'Endoso en retorno'; $etiqueta273->activo = 1;  $etiqueta273->save();
        $etiqueta274 = new news_etiquetas(); $etiqueta274->etiqueta = 'Endoso fiduciario'; $etiqueta274->activo = 1;  $etiqueta274->save();
        $etiqueta275 = new news_etiquetas(); $etiqueta275->etiqueta = 'Enfoque económico'; $etiqueta275->activo = 1;  $etiqueta275->save();
        $etiqueta276 = new news_etiquetas(); $etiqueta276->etiqueta = 'Entidades locales'; $etiqueta276->activo = 1;  $etiqueta276->save();
        $etiqueta277 = new news_etiquetas(); $etiqueta277->etiqueta = 'Equipo autorizado'; $etiqueta277->activo = 1;  $etiqueta277->save();
        $etiqueta278 = new news_etiquetas(); $etiqueta278->etiqueta = 'Error in personae'; $etiqueta278->activo = 1;  $etiqueta278->save();
        $etiqueta279 = new news_etiquetas(); $etiqueta279->etiqueta = 'Error perjudicial'; $etiqueta279->activo = 1;  $etiqueta279->save();
        $etiqueta280 = new news_etiquetas(); $etiqueta280->etiqueta = 'Escritura pública'; $etiqueta280->activo = 1;  $etiqueta280->save();
        $etiqueta281 = new news_etiquetas(); $etiqueta281->etiqueta = 'Esperanza de vida'; $etiqueta281->activo = 1;  $etiqueta281->save();
        $etiqueta282 = new news_etiquetas(); $etiqueta282->etiqueta = 'Institucionalidad'; $etiqueta282->activo = 1;  $etiqueta282->save();
        $etiqueta283 = new news_etiquetas(); $etiqueta283->etiqueta = 'Interculturalidad'; $etiqueta283->activo = 1;  $etiqueta283->save();
        $etiqueta284 = new news_etiquetas(); $etiqueta284->etiqueta = 'Interés moratorio'; $etiqueta284->activo = 1;  $etiqueta284->save();
        $etiqueta285 = new news_etiquetas(); $etiqueta285->etiqueta = 'Internacionalismo'; $etiqueta285->activo = 1;  $etiqueta285->save();
        $etiqueta286 = new news_etiquetas(); $etiqueta286->etiqueta = 'Lenguaje político'; $etiqueta286->activo = 1;  $etiqueta286->save();
        $etiqueta287 = new news_etiquetas(); $etiqueta287->etiqueta = 'Soberanía popular'; $etiqueta287->activo = 1;  $etiqueta287->save();
        $etiqueta288 = new news_etiquetas(); $etiqueta288->etiqueta = 'Autonomía cultural'; $etiqueta288->activo = 1;  $etiqueta288->save();
        $etiqueta289 = new news_etiquetas(); $etiqueta289->etiqueta = 'Autonomía personal'; $etiqueta289->activo = 1;  $etiqueta289->save();
        $etiqueta290 = new news_etiquetas(); $etiqueta290->etiqueta = 'Autonomía política'; $etiqueta290->activo = 1;  $etiqueta290->save();
        $etiqueta291 = new news_etiquetas(); $etiqueta291->etiqueta = 'Democracia directa'; $etiqueta291->activo = 1;  $etiqueta291->save();
        $etiqueta292 = new news_etiquetas(); $etiqueta292->etiqueta = 'Derecho de trabajo'; $etiqueta292->activo = 1;  $etiqueta292->save();
        $etiqueta293 = new news_etiquetas(); $etiqueta293->etiqueta = 'Derecho supletorio'; $etiqueta293->activo = 1;  $etiqueta293->save();
        $etiqueta294 = new news_etiquetas(); $etiqueta294->etiqueta = 'Derecho sustantivo'; $etiqueta294->activo = 1;  $etiqueta294->save();
        $etiqueta295 = new news_etiquetas(); $etiqueta295->etiqueta = 'Derecho tributario'; $etiqueta295->activo = 1;  $etiqueta295->save();
        $etiqueta296 = new news_etiquetas(); $etiqueta296->etiqueta = 'Derechos políticos'; $etiqueta296->activo = 1;  $etiqueta296->save();
        $etiqueta297 = new news_etiquetas(); $etiqueta297->etiqueta = 'Diagrama de pareto'; $etiqueta297->activo = 1;  $etiqueta297->save();
        $etiqueta298 = new news_etiquetas(); $etiqueta298->etiqueta = 'Dinámica económica'; $etiqueta298->activo = 1;  $etiqueta298->save();
        $etiqueta299 = new news_etiquetas(); $etiqueta299->etiqueta = 'Distrito electoral'; $etiqueta299->activo = 1;  $etiqueta299->save();
        $etiqueta300 = new news_etiquetas(); $etiqueta300->etiqueta = 'Efectos del endoso'; $etiqueta300->activo = 1;  $etiqueta300->save();
        $etiqueta301 = new news_etiquetas(); $etiqueta301->etiqueta = 'Elección indirecta'; $etiqueta301->activo = 1;  $etiqueta301->save();
        $etiqueta302 = new news_etiquetas(); $etiqueta302->etiqueta = 'Empresa del estado'; $etiqueta302->activo = 1;  $etiqueta302->save();
        $etiqueta303 = new news_etiquetas(); $etiqueta303->etiqueta = 'Especies anadromas'; $etiqueta303->activo = 1;  $etiqueta303->save();
        $etiqueta304 = new news_etiquetas(); $etiqueta304->etiqueta = 'Integración racial'; $etiqueta304->activo = 1;  $etiqueta304->save();
        $etiqueta305 = new news_etiquetas(); $etiqueta305->etiqueta = 'Interacción social'; $etiqueta305->activo = 1;  $etiqueta305->save();
        $etiqueta306 = new news_etiquetas(); $etiqueta306->etiqueta = 'Políticas públicas'; $etiqueta306->activo = 1;  $etiqueta306->save();
        $etiqueta307 = new news_etiquetas(); $etiqueta307->etiqueta = 'Prudencia política'; $etiqueta307->activo = 1;  $etiqueta307->save();
        $etiqueta308 = new news_etiquetas(); $etiqueta308->etiqueta = 'Respeto a sí mismo'; $etiqueta308->activo = 1;  $etiqueta308->save();
        $etiqueta309 = new news_etiquetas(); $etiqueta309->etiqueta = 'Virtudes políticas'; $etiqueta309->activo = 1;  $etiqueta309->save();
        $etiqueta310 = new news_etiquetas(); $etiqueta310->etiqueta = 'Ciudadanía integral'; $etiqueta310->activo = 1;  $etiqueta310->save();
        $etiqueta311 = new news_etiquetas(); $etiqueta311->etiqueta = 'Consensos políticos'; $etiqueta311->activo = 1;  $etiqueta311->save();
        $etiqueta312 = new news_etiquetas(); $etiqueta312->etiqueta = 'Derecho de sufragio'; $etiqueta312->activo = 1;  $etiqueta312->save();
        $etiqueta313 = new news_etiquetas(); $etiqueta313->etiqueta = 'Derecho potestativo'; $etiqueta313->activo = 1;  $etiqueta313->save();
        $etiqueta314 = new news_etiquetas(); $etiqueta314->etiqueta = 'Derecho transitorio'; $etiqueta314->activo = 1;  $etiqueta314->save();
        $etiqueta315 = new news_etiquetas(); $etiqueta315->etiqueta = 'Derechos culturales'; $etiqueta315->activo = 1;  $etiqueta315->save();
        $etiqueta316 = new news_etiquetas(); $etiqueta316->etiqueta = 'Desobediencia civil'; $etiqueta316->activo = 1;  $etiqueta316->save();
        $etiqueta317 = new news_etiquetas(); $etiqueta317->etiqueta = 'Diligencia judicial'; $etiqueta317->activo = 1;  $etiqueta317->save();
        $etiqueta318 = new news_etiquetas(); $etiqueta318->etiqueta = 'Diligencias previas'; $etiqueta318->activo = 1;  $etiqueta318->save();
        $etiqueta319 = new news_etiquetas(); $etiqueta319->etiqueta = 'Disparador afectivo'; $etiqueta319->activo = 1;  $etiqueta319->save();
        $etiqueta320 = new news_etiquetas(); $etiqueta320->etiqueta = 'Disparador cultural'; $etiqueta320->activo = 1;  $etiqueta320->save();
        $etiqueta321 = new news_etiquetas(); $etiqueta321->etiqueta = 'Distrito uninominal'; $etiqueta321->activo = 1;  $etiqueta321->save();
        $etiqueta322 = new news_etiquetas(); $etiqueta322->etiqueta = 'División de poderes'; $etiqueta322->activo = 1;  $etiqueta322->save();
        $etiqueta323 = new news_etiquetas(); $etiqueta323->etiqueta = 'Documento auténtico'; $etiqueta323->activo = 1;  $etiqueta323->save();
        $etiqueta324 = new news_etiquetas(); $etiqueta324->etiqueta = 'Documento ejecutivo'; $etiqueta324->activo = 1;  $etiqueta324->save();
        $etiqueta325 = new news_etiquetas(); $etiqueta325->etiqueta = 'Documentos agrarios'; $etiqueta325->activo = 1;  $etiqueta325->save();
        $etiqueta326 = new news_etiquetas(); $etiqueta326->etiqueta = 'Dominio de sí mismo'; $etiqueta326->activo = 1;  $etiqueta326->save();
        $etiqueta327 = new news_etiquetas(); $etiqueta327->etiqueta = 'Donación inoficiosa'; $etiqueta327->activo = 1;  $etiqueta327->save();
        $etiqueta328 = new news_etiquetas(); $etiqueta328->etiqueta = 'Economías de escala'; $etiqueta328->activo = 1;  $etiqueta328->save();
        $etiqueta329 = new news_etiquetas(); $etiqueta329->etiqueta = 'Educar para la vida'; $etiqueta329->activo = 1;  $etiqueta329->save();
        $etiqueta330 = new news_etiquetas(); $etiqueta330->etiqueta = 'Ejecución del laudo'; $etiqueta330->activo = 1;  $etiqueta330->save();
        $etiqueta331 = new news_etiquetas(); $etiqueta331->etiqueta = 'Endoso en propiedad'; $etiqueta331->activo = 1;  $etiqueta331->save();
        $etiqueta332 = new news_etiquetas(); $etiqueta332->etiqueta = 'Endoso pignoraticio'; $etiqueta332->activo = 1;  $etiqueta332->save();
        $etiqueta333 = new news_etiquetas(); $etiqueta333->etiqueta = 'Entidad aseguradora'; $etiqueta333->activo = 1;  $etiqueta333->save();
        $etiqueta334 = new news_etiquetas(); $etiqueta334->etiqueta = 'Espacio humanitario'; $etiqueta334->activo = 1;  $etiqueta334->save();
        $etiqueta335 = new news_etiquetas(); $etiqueta335->etiqueta = 'Estructura orgánica'; $etiqueta335->activo = 1;  $etiqueta335->save();
        $etiqueta336 = new news_etiquetas(); $etiqueta336->etiqueta = 'Integrae sententiae'; $etiqueta336->activo = 1;  $etiqueta336->save();
        $etiqueta337 = new news_etiquetas(); $etiqueta337->etiqueta = 'Interposita persona'; $etiqueta337->activo = 1;  $etiqueta337->save();
        $etiqueta338 = new news_etiquetas(); $etiqueta338->etiqueta = 'Respeto a los demás'; $etiqueta338->activo = 1;  $etiqueta338->save();
        $etiqueta339 = new news_etiquetas(); $etiqueta339->etiqueta = 'Derecho de propiedad'; $etiqueta339->activo = 1;  $etiqueta339->save();
        $etiqueta340 = new news_etiquetas(); $etiqueta340->etiqueta = 'Desarrollo económico'; $etiqueta340->activo = 1;  $etiqueta340->save();
        $etiqueta341 = new news_etiquetas(); $etiqueta341->etiqueta = 'Desechos radiactivos'; $etiqueta341->activo = 1;  $etiqueta341->save();
        $etiqueta342 = new news_etiquetas(); $etiqueta342->etiqueta = 'Dibujos industriales'; $etiqueta342->activo = 1;  $etiqueta342->save();
        $etiqueta343 = new news_etiquetas(); $etiqueta343->etiqueta = 'Disparador de status'; $etiqueta343->activo = 1;  $etiqueta343->save();
        $etiqueta344 = new news_etiquetas(); $etiqueta344->etiqueta = 'División del trabajo'; $etiqueta344->activo = 1;  $etiqueta344->save();
        $etiqueta345 = new news_etiquetas(); $etiqueta345->etiqueta = 'Donación condicional'; $etiqueta345->activo = 1;  $etiqueta345->save();
        $etiqueta346 = new news_etiquetas(); $etiqueta346->etiqueta = 'Economía deficitaria'; $etiqueta346->activo = 1;  $etiqueta346->save();
        $etiqueta347 = new news_etiquetas(); $etiqueta347->etiqueta = 'Empresa de una parte'; $etiqueta347->activo = 1;  $etiqueta347->save();
        $etiqueta348 = new news_etiquetas(); $etiqueta348->etiqueta = 'Encuesta en vivienda'; $etiqueta348->activo = 1;  $etiqueta348->save();
        $etiqueta349 = new news_etiquetas(); $etiqueta349->etiqueta = 'Encuestas de campaña'; $etiqueta349->activo = 1;  $etiqueta349->save();
        $etiqueta350 = new news_etiquetas(); $etiqueta350->etiqueta = 'Energía no renovable'; $etiqueta350->activo = 1;  $etiqueta350->save();
        $etiqueta351 = new news_etiquetas(); $etiqueta351->etiqueta = 'Enfoque politilógico'; $etiqueta351->activo = 1;  $etiqueta351->save();
        $etiqueta352 = new news_etiquetas(); $etiqueta352->etiqueta = 'Entidad adjudicadora'; $etiqueta352->activo = 1;  $etiqueta352->save();
        $etiqueta353 = new news_etiquetas(); $etiqueta353->etiqueta = 'Escrutinio y cómputo'; $etiqueta353->activo = 1;  $etiqueta353->save();
        $etiqueta354 = new news_etiquetas(); $etiqueta354->etiqueta = 'Identidades sociales'; $etiqueta354->activo = 1;  $etiqueta354->save();
        $etiqueta355 = new news_etiquetas(); $etiqueta355->etiqueta = 'Intercambio de notas'; $etiqueta355->activo = 1;  $etiqueta355->save();
        $etiqueta356 = new news_etiquetas(); $etiqueta356->etiqueta = 'Interdictum savianum'; $etiqueta356->activo = 1;  $etiqueta356->save();
        $etiqueta357 = new news_etiquetas(); $etiqueta357->etiqueta = 'Interés convencional'; $etiqueta357->activo = 1;  $etiqueta357->save();
        $etiqueta358 = new news_etiquetas(); $etiqueta358->etiqueta = 'Legitimidad política'; $etiqueta358->activo = 1;  $etiqueta358->save();
        $etiqueta359 = new news_etiquetas(); $etiqueta359->etiqueta = 'Política comparativa'; $etiqueta359->activo = 1;  $etiqueta359->save();
        $etiqueta360 = new news_etiquetas(); $etiqueta360->etiqueta = 'Servicio democrático'; $etiqueta360->activo = 1;  $etiqueta360->save();
        $etiqueta361 = new news_etiquetas(); $etiqueta361->etiqueta = 'Vigilancia ciudadana'; $etiqueta361->activo = 1;  $etiqueta361->save();
        $etiqueta362 = new news_etiquetas(); $etiqueta362->etiqueta = 'Derecho de superficie'; $etiqueta362->activo = 1;  $etiqueta362->save();
        $etiqueta363 = new news_etiquetas(); $etiqueta363->etiqueta = 'Derecho parlamentario'; $etiqueta363->activo = 1;  $etiqueta363->save();
        $etiqueta364 = new news_etiquetas(); $etiqueta364->etiqueta = 'Derecho penitenciario'; $etiqueta364->activo = 1;  $etiqueta364->save();
        $etiqueta365 = new news_etiquetas(); $etiqueta365->etiqueta = 'Derecho personalíslmo'; $etiqueta365->activo = 1;  $etiqueta365->save();
        $etiqueta366 = new news_etiquetas(); $etiqueta366->etiqueta = 'Destitución de empleo'; $etiqueta366->activo = 1;  $etiqueta366->save();
        $etiqueta367 = new news_etiquetas(); $etiqueta367->etiqueta = 'Difusión del impuesto'; $etiqueta367->activo = 1;  $etiqueta367->save();
        $etiqueta368 = new news_etiquetas(); $etiqueta368->etiqueta = 'Distrito plurinominal'; $etiqueta368->activo = 1;  $etiqueta368->save();
        $etiqueta369 = new news_etiquetas(); $etiqueta369->etiqueta = 'Diversidad biológica '; $etiqueta369->activo = 1;  $etiqueta369->save();
        $etiqueta370 = new news_etiquetas(); $etiqueta370->etiqueta = 'Economía de impuestos'; $etiqueta370->activo = 1;  $etiqueta370->save();
        $etiqueta371 = new news_etiquetas(); $etiqueta371->etiqueta = 'Encargado de negocios'; $etiqueta371->activo = 1;  $etiqueta371->save();
        $etiqueta372 = new news_etiquetas(); $etiqueta372->etiqueta = 'Encuestas electorales'; $etiqueta372->activo = 1;  $etiqueta372->save();
        $etiqueta373 = new news_etiquetas(); $etiqueta373->etiqueta = 'Encuestas telefónicas'; $etiqueta373->activo = 1;  $etiqueta373->save();
        $etiqueta374 = new news_etiquetas(); $etiqueta374->etiqueta = 'Endoso Requisitos del'; $etiqueta374->activo = 1;  $etiqueta374->save();
        $etiqueta375 = new news_etiquetas(); $etiqueta375->etiqueta = 'Enfermedad de trabajo'; $etiqueta375->activo = 1;  $etiqueta375->save();
        $etiqueta376 = new news_etiquetas(); $etiqueta376->etiqueta = 'Ensayo no destructivo'; $etiqueta376->activo = 1;  $etiqueta376->save();
        $etiqueta377 = new news_etiquetas(); $etiqueta377->etiqueta = 'Integración económica'; $etiqueta377->activo = 1;  $etiqueta377->save();
        $etiqueta378 = new news_etiquetas(); $etiqueta378->etiqueta = 'Balance de actividades'; $etiqueta378->activo = 1;  $etiqueta378->save();
        $etiqueta379 = new news_etiquetas(); $etiqueta379->etiqueta = 'Balance de poder poder'; $etiqueta379->activo = 1;  $etiqueta379->save();
        $etiqueta380 = new news_etiquetas(); $etiqueta380->etiqueta = 'Compromiso democrático'; $etiqueta380->activo = 1;  $etiqueta380->save();
        $etiqueta381 = new news_etiquetas(); $etiqueta381->etiqueta = 'Derecho procesal penal'; $etiqueta381->activo = 1;  $etiqueta381->save();
        $etiqueta382 = new news_etiquetas(); $etiqueta382->etiqueta = 'Desarrollo comunitario'; $etiqueta382->activo = 1;  $etiqueta382->save();
        $etiqueta383 = new news_etiquetas(); $etiqueta383->etiqueta = 'Desarrollo sustentable'; $etiqueta383->activo = 1;  $etiqueta383->save();
        $etiqueta384 = new news_etiquetas(); $etiqueta384->etiqueta = 'Desviación de comercio'; $etiqueta384->activo = 1;  $etiqueta384->save();
        $etiqueta385 = new news_etiquetas(); $etiqueta385->etiqueta = 'Diputados uninominales'; $etiqueta385->activo = 1;  $etiqueta385->save();
        $etiqueta386 = new news_etiquetas(); $etiqueta386->etiqueta = 'Disposición a cooperar'; $etiqueta386->activo = 1;  $etiqueta386->save();
        $etiqueta387 = new news_etiquetas(); $etiqueta387->etiqueta = 'Economía superavitaria'; $etiqueta387->activo = 1;  $etiqueta387->save();
        $etiqueta388 = new news_etiquetas(); $etiqueta388->etiqueta = 'Elasticidad de demanda'; $etiqueta388->activo = 1;  $etiqueta388->save();
        $etiqueta389 = new news_etiquetas(); $etiqueta389->etiqueta = 'Enfoque organizacional'; $etiqueta389->activo = 1;  $etiqueta389->save();
        $etiqueta390 = new news_etiquetas(); $etiqueta390->etiqueta = 'Entredicho provisional'; $etiqueta390->activo = 1;  $etiqueta390->save();
        $etiqueta391 = new news_etiquetas(); $etiqueta391->etiqueta = 'Especificación técnica'; $etiqueta391->activo = 1;  $etiqueta391->save();
        $etiqueta392 = new news_etiquetas(); $etiqueta392->etiqueta = 'Instituciones formales'; $etiqueta392->activo = 1;  $etiqueta392->save();
        $etiqueta393 = new news_etiquetas(); $etiqueta393->etiqueta = 'Participación política'; $etiqueta393->activo = 1;  $etiqueta393->save();
        $etiqueta394 = new news_etiquetas(); $etiqueta394->etiqueta = 'Secretaria de economia'; $etiqueta394->activo = 1;  $etiqueta394->save();
        $etiqueta395 = new news_etiquetas(); $etiqueta395->etiqueta = 'Sentido de la justicia'; $etiqueta395->activo = 1;  $etiqueta395->save();
        $etiqueta396 = new news_etiquetas(); $etiqueta396->etiqueta = 'Cultura de la legalidad'; $etiqueta396->activo = 1;  $etiqueta396->save();
        $etiqueta397 = new news_etiquetas(); $etiqueta397->etiqueta = 'Descripción arancelaria'; $etiqueta397->activo = 1;  $etiqueta397->save();
        $etiqueta398 = new news_etiquetas(); $etiqueta398->etiqueta = 'Desregulación económica'; $etiqueta398->activo = 1;  $etiqueta398->save();
        $etiqueta399 = new news_etiquetas(); $etiqueta399->etiqueta = 'Discernimiento político'; $etiqueta399->activo = 1;  $etiqueta399->save();
        $etiqueta400 = new news_etiquetas(); $etiqueta400->etiqueta = 'Disparador de necesidad'; $etiqueta400->activo = 1;  $etiqueta400->save();
        $etiqueta401 = new news_etiquetas(); $etiqueta401->etiqueta = 'Distribución al público'; $etiqueta401->activo = 1;  $etiqueta401->save();
        $etiqueta402 = new news_etiquetas(); $etiqueta402->etiqueta = 'Endocrinología criminal'; $etiqueta402->activo = 1;  $etiqueta402->save();
        $etiqueta403 = new news_etiquetas(); $etiqueta403->etiqueta = 'Enriquecimiento ilícito'; $etiqueta403->activo = 1;  $etiqueta403->save();
        $etiqueta404 = new news_etiquetas(); $etiqueta404->etiqueta = 'Espacio ultra terrestre'; $etiqueta404->activo = 1;  $etiqueta404->save();
        $etiqueta405 = new news_etiquetas(); $etiqueta405->etiqueta = 'Inter arma silent leges'; $etiqueta405->activo = 1;  $etiqueta405->save();
        $etiqueta406 = new news_etiquetas(); $etiqueta406->etiqueta = 'Intercambio de escritos'; $etiqueta406->activo = 1;  $etiqueta406->save();
        $etiqueta407 = new news_etiquetas(); $etiqueta407->etiqueta = 'Interdictum de precario'; $etiqueta407->activo = 1;  $etiqueta407->save();
        $etiqueta408 = new news_etiquetas(); $etiqueta408->etiqueta = 'Interpretar un contrato'; $etiqueta408->activo = 1;  $etiqueta408->save();
        $etiqueta409 = new news_etiquetas(); $etiqueta409->etiqueta = 'Desgravación arancelaria'; $etiqueta409->activo = 1;  $etiqueta409->save();
        $etiqueta410 = new news_etiquetas(); $etiqueta410->etiqueta = 'Determinación tributaria'; $etiqueta410->activo = 1;  $etiqueta410->save();
        $etiqueta411 = new news_etiquetas(); $etiqueta411->etiqueta = 'Diagrama de causa-efecto'; $etiqueta411->activo = 1;  $etiqueta411->save();
        $etiqueta412 = new news_etiquetas(); $etiqueta412->etiqueta = 'Diligencias preliminares'; $etiqueta412->activo = 1;  $etiqueta412->save();
        $etiqueta413 = new news_etiquetas(); $etiqueta413->etiqueta = 'Diputados plurinominales'; $etiqueta413->activo = 1;  $etiqueta413->save();
        $etiqueta414 = new news_etiquetas(); $etiqueta414->etiqueta = 'Dispositivo de seguridad'; $etiqueta414->activo = 1;  $etiqueta414->save();
        $etiqueta415 = new news_etiquetas(); $etiqueta415->etiqueta = 'Economía de la migración'; $etiqueta415->activo = 1;  $etiqueta415->save();
        $etiqueta416 = new news_etiquetas(); $etiqueta416->etiqueta = 'Encuestas de seguimiento'; $etiqueta416->activo = 1;  $etiqueta416->save();
        $etiqueta417 = new news_etiquetas(); $etiqueta417->etiqueta = 'Encuestas preelectorales'; $etiqueta417->activo = 1;  $etiqueta417->save();
        $etiqueta418 = new news_etiquetas(); $etiqueta418->etiqueta = 'Endoso en administración'; $etiqueta418->activo = 1;  $etiqueta418->save();
        $etiqueta419 = new news_etiquetas(); $etiqueta419->etiqueta = 'Endoso por representante'; $etiqueta419->activo = 1;  $etiqueta419->save();
        $etiqueta420 = new news_etiquetas(); $etiqueta420->etiqueta = 'Especificidad científica'; $etiqueta420->activo = 1;  $etiqueta420->save();
        $etiqueta421 = new news_etiquetas(); $etiqueta421->etiqueta = 'Instituciones informales'; $etiqueta421->activo = 1;  $etiqueta421->save();
        $etiqueta422 = new news_etiquetas(); $etiqueta422->etiqueta = 'Interdictum demolitorium'; $etiqueta422->activo = 1;  $etiqueta422->save();
        $etiqueta423 = new news_etiquetas(); $etiqueta423->etiqueta = 'Democracia representativa'; $etiqueta423->activo = 1;  $etiqueta423->save();
        $etiqueta424 = new news_etiquetas(); $etiqueta424->etiqueta = 'Derecho de representación'; $etiqueta424->activo = 1;  $etiqueta424->save();



    }
}
